# Generated by Django 2.2.4 on 2020-01-07 13:45

from django.db import migrations, models
import morae.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('gmoney', models.CharField(max_length=200)),
                ('kmoney', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('gphoto', models.ImageField(upload_to=morae.models.user_path)),
                ('tphoto', models.ImageField(upload_to=morae.models.user_path)),
                ('detail', models.CharField(max_length=200)),
                ('kakao', models.CharField(max_length=200)),
            ],
        ),
    ]
