# Generated by Django 2.2.4 on 2020-01-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='state',
            field=models.CharField(max_length=4),
        ),
    ]
