# Generated by Django 2.2.4 on 2020-01-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morae', '0002_auto_20200107_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='location',
            new_name='address',
        ),
    ]
