# Generated by Django 2.2.4 on 2020-01-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morae', '0005_auto_20200108_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='writepw',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
